### ISSUE TITLE
Problem compiling with gpsd

### ISSUE THREAD

**Issue by aerostitch** [aerostitch/testnavit#1306]
*Issue migrated from trac ticket # 1284*

**component:** core | **priority:** major

#### 2015-03-17 22:56:41: mmmarquinez@gmail.com created the issue

___
Hi
When I try to compile navit with gpsd-3.13 I got the next crash:
[  0%] Building C object navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/vehicle_gpsd.c.o

Building C object navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/vehicle_gpsd.c.o
/var/tmp/portage/app-misc/navit-svn-99999999/work/navit-svn-99999999/navit/vehicle/gpsd/vehicle_gpsd.c: In function 'vehicle_gpsd_callback':
/var/tmp/portage/app-misc/navit-svn-99999999/work/navit-svn-99999999/navit/vehicle/gpsd/vehicle_gpsd.c:133:40: error: 'struct gps_data_t' has no member named 'ss'
                                if (data->ss[i] > 0)

Compilation works with gpsd-3.11
Thank you
