### ISSUE TITLE
Problem compiling with gpsd

### ISSUE THREAD

**Issue by aerostitch** [aerostitch/testnavit#262]
*Issue migrated from trac ticket # 1284*

**component:** core | **priority:** major

#### 2015-03-17 22:56:41: mmmarquinez@gmail.com created the issue

___
> Hi
> When I try to compile navit with gpsd-3.13 I got the next crash:
> [  0%] Building C object navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/vehicle_gpsd.c.o
> 
> Building C object navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/vehicle_gpsd.c.o
> /var/tmp/portage/app-misc/navit-svn-99999999/work/navit-svn-99999999/navit/vehicle/gpsd/vehicle_gpsd.c: In function 'vehicle_gpsd_callback':
> /var/tmp/portage/app-misc/navit-svn-99999999/work/navit-svn-99999999/navit/vehicle/gpsd/vehicle_gpsd.c:133:40: error: 'struct gps_data_t' has no member named 'ss'
>                                 if (data->ss[i] > 0)
> 
> 
> Compilation works with gpsd-3.11
> Thank you

**Comment by aerostitch** [comment]
#### 2015-03-22 05:36:56: @sleske commented


___
> Yes, it looks like 'struct gps_data_t' changed in gpsd V3.12. We'll have to adapt the code.
> Ideally in a way that works with both old and new libgpsd...
> 
> This is documented in gps.h:
> 
> 
> ```
> Major Version 6:
> 
> [...]
> The shape of the skyview structure has changed to make working with the
> satellites-used bits less confusing.
> (January 2015, release 3.12).
> ```
>

**Comment by aerostitch** [comment]
#### 2015-03-22 05:36:56: @sleske

**Comment by aerostitch** [comment]
#### 2015-04-03 01:03:27: turulomio@yahoo.es commented


___
> Hi again
> 
> I'm  not an expert of gpsd
> 
> I've been searching the code and the atribute ss has been removed in gpsd>3.11.
> 
> The ss atribute has a signal-to-noise ratio (dB) as you can see in http://sourcecodebrowser.com/gpsd/2.95/gps_8h_source.html#l01014
> 
> I think that ratio is now in rtcm2_t struct in atribute snr
> 
> I replace the line if (data->ss[i]>0) with
>  if (data->rtcm2.conhealth.sat[i].snr!=-1)
> 
> It compiles, I hope this can help
> 
> Thank you
